# version: '3.8'

# services:
#   mqtt-broker:
#     image: eclipse-mosquitto:2.0.15
#     container_name: mosquitto-broker
#     restart: unless-stopped
#     ports:
#       - "1883:1883" # MQTT Standardport
#       - "9001:9001" # Websockets-Port
#     volumes:
#       - ./mosquitto/config:/mosquitto/config
#       - ./mosquitto/data:/mosquitto/data
#       - ./mosquitto/log:/mosquitto/log
#     environment:
#       - INITIAL_USER=${MQTT_USER:-admin}
#       - INITIAL_PASSWORD=${MQTT_PASSWORD:-changeme}
#     entrypoint: |
#       sh -c 'chown mosquitto:mosquitto /mosquitto/config/pwfile;
#       if [ ! -s /mosquitto/config/pwfile ]; then
#         mosquitto_passwd -b -c /mosquitto/config/pwfile $${INITIAL_USER} $${INITIAL_PASSWORD};
#       fi;
#       exec /docker-entrypoint.sh mosquitto -c /mosquitto/config/mosquitto.conf'


